version: 0.0
os: linux
files:
  - source: ./automated-testing-processor
    destination: /home/ubuntu/automated-testing-processor
permissions:
  - object: /home/ubuntu/automated-testing-processor
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: remote-cmd-install-dependencies.sh
      runas: ubuntu
  ApplicationStart:
    - location: remote-cmd-reload-app.sh
      runas: ubuntu
