version: 0.0
os: linux
files:
  - source: ./direct.jar
    destination: /home/direct/direct_backup/
permissions:
  - object: /home/direct/direct_backup
    pattern: "direct.jar"
    owner: direct
    group: rvm
hooks:
  ApplicationStart:
    - location: remote-cmd-start-app.sh
      runas: direct
